// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewApplication.Models;

namespace NewApplication.Migrations
{
    [DbContext(typeof(SignupContext))]
    [Migration("20201228124126_newcreatetable")]
    partial class newcreatetable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NewApplication.Models.MultipleFilesUpload", b =>
                {
                    b.Property<int>("Files_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Files_Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("signupsUserId")
                        .HasColumnType("int");

                    b.HasKey("Files_Id");

                    b.HasIndex("signupsUserId");

                    b.ToTable("multipleFilesUploads");
                });

            modelBuilder.Entity("NewApplication.Models.Signup", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Signups");
                });

            modelBuilder.Entity("NewApplication.Models.MultipleFilesUpload", b =>
                {
                    b.HasOne("NewApplication.Models.Signup", "signups")
                        .WithMany("multipleFilesUploads")
                        .HasForeignKey("signupsUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("signups");
                });

            modelBuilder.Entity("NewApplication.Models.Signup", b =>
                {
                    b.Navigation("multipleFilesUploads");
                });
#pragma warning restore 612, 618
        }
    }
}
